debug: true

#Particles directory (twig namespace "@template")
particles: "particles"

#View directory (twig namespace "@template")
views: "views"

#Cache directory
cache: "cache"

#TODO: create configs for simple register sidebars
#widgets: